#pragma once

enum class UIEventId {
    NONE,
    BUTTON_RELEASE_SELECT,
    BUTTON_RELEASE_UP,
    BUTTON_RELEASE_DOWN,
    BUTTON_RELEASE_LEFT,
    BUTTON_RELEASE_RIGHT,
    BUTTON_HELD_SELECT,
    BUTTON_HELD_UP,
    BUTTON_HELD_DOWN,
    BUTTON_HELD_LEFT,
    BUTTON_HELD_RIGHT,
};

